project_name: somechain

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy -compat=1.18

builds:
  - id: ubuntu-amd64
    main: ./cmd/somechaind
    binary: somechaind
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - GO111MODULE=on
    flags:
      - -mod=readonly
    ldflags:
      - -s -w
      - -X github.com/cosmos/cosmos-sdk/version.Name=somechain
      - -X github.com/cosmos/cosmos-sdk/version.AppName=somechain
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}

  # - id: ubuntu-arm64
  #   main: ./cmd/somechaind
  #   binary: somechaind
  #   goos:
  #     - linux
  #   goarch:
  #     - arm64
  #   flags:
  #     - -mod=readonly
  #   ldflags:
  #     - -s -w
  #     - -X github.com/cosmos/cosmos-sdk/version.Name=somechain 
  #     - -X github.com/cosmos/cosmos-sdk/version.AppName=somechain 
  #     - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }}
  #     - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}

  # - id: darwin-amd64
  #   main: ./cmd/somechaind
  #   binary: somechaind
  #   goos:
  #     - darwin
  #   goarch:
  #     - arm64
  #   flags:
  #     - -mod=readonly
  #   ldflags:
  #     - -s -w
  #     - -X github.com/cosmos/cosmos-sdk/version.Name=somechain 
  #     - -X github.com/cosmos/cosmos-sdk/version.AppName=somechain 
  #     - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }}
  #     - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}

dockers:
  - image_templates: ["ghcr.io/arnabghose997/{{ .ProjectName }}:{{ .Version }}-amd64"]
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
    - --platform=linux/amd64
    - --label=org.opencontainers.label=image.title={{ .ProjectName }}
    - --label=org.opencontainers.label=image.description={{ .ProjectName }}
    - --label=org.opencontainers.label=image.url=https://github.com/arnabghose997/{{ .ProjectName }}
    - --label=org.opencontainers.label=image.source=https://github.com/arnabghose997/{{ .ProjectName }}
    - --label=org.opencontainers.label=image.version={{ .Version }}
    - --label=org.opencontainers.label=image.revision={{ .FullCommit }}
    - --label=org.opencontainers.label=image.licenses=MIT
  # - image_templates: ["ghcr.io/arnabghose997/{{ .ProjectName }}:{{ .Version }}-arm64v8"]
  #   dockerfile: Dockerfile
  #   use: buildx
  #   build_flag_templates:
  #   - --platform=linux/arm64/v8
  #   - --label=org.opencontainers.label=image.title={{ .ProjectName }}
  #   - --label=org.opencontainers.label=image.description={{ .ProjectName }}
  #   - --label=org.opencontainers.label=image.url=https://github.com/arnabghose997/{{ .ProjectName }}
  #   - --label=org.opencontainers.label=image.source=https://github.com/arnabghose997/{{ .ProjectName }}
  #   - --label=org.opencontainers.label=image.version={{ .Version }}
  #   - --label=org.opencontainers.label=image.licenses=MIT

archives:
  - id: release-archives
    format: tar.gz
    wrap_in_directory: true
    name_template: "{{ .Binary }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    files:
      - README.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: arnabghose997
    name: somechain
  
  draft: false
  prerelease: false
  mode: append
  header: |
    # Release Notes for {{.ProjectName}} v{{.Version}}