name: Build
on:
  push:
    branches: [ v* ]
  pull_request:
    branches: [ master, v* ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Generate Protobuf Golang Code
        run: protoc
       
      - name: Build
        run: make build