name: Lint

on:
  pull_request:
  push:
    branches: [ main ]

permission:
  contents: read

jobs:
  golangci:
    name: Golang Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # - uses: technote-space/get-diff-action@v4
      #   with:
      #     PATTERN: |
      #       .go
      #       .mod
      #       .sum

      - uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout 10m
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: latest